export const catsData = [
  {
    emotionTags: ['moody'],
    isGif: false,
    image: 'angry.jpeg',
    alt: 'A cat looking moody',
  },
  {
    emotionTags: ['moody'],
    isGif: false,
    image: 'angry3.jpeg',
    alt: 'A cat looking moody',
  },

  {
    emotionTags: ['moody'],
    isGif: false,
    image: 'moody.jpg',
    alt: 'A cat looking moody',
  },
  {
    emotionTags: ['moody'],
    isGif: true,
    image: 'angry.gif',
    alt: 'A cat looking moody',
  },
  {
    emotionTags: ['moody'],
    isGif: false,
    image: 'moody2.gif',
    alt: 'A cat looking moody',
  },
  {
    emotionTags: ['moody'],
    isGif: false,
    image: 'moody3.jpeg',
    alt: 'A cat looking moody',
  },
  {
    emotionTags: ['moody'],
    isGif: true,
    image: 'moody.gif',
    alt: 'A cat looking moody',
  },
  {
    emotionTags: ['moody'],
    isGif: true,
    image: 'angry2.gif',
    alt: 'A cat looking angry',
  },
  {
    emotionTags: ['moody', 'insomniac'],
    isGif: false,
    image: 'angry2.jpeg',
    alt: 'A cat looking moody',
  },
  {
    emotionTags: ['insomniac'],
    isGif: false,
    image: 'insomnia3.jpeg',
    alt: 'A cat looking insomniac',
  },
  {
    emotionTags: ['insomniac'],
    isGif: false,
    image: 'insomnia.jpeg',
    alt: 'A cat looking insomniac',
  },
  {
    emotionTags: ['insomniac'],
    isGif: false,
    image: 'insomnia2.jpeg',
    alt: 'A cat looking insomniac',
  },
  {
    emotionTags: ['insomniac'],
    isGif: false,
    image: 'insomnia1.jpeg',
    alt: 'A cat looking insomniac',
  },
  {
    emotionTags: ['insomniac'],
    isGif: true,
    image: 'insomnia2.gif',
    alt: 'A cat looking insomniac',
  },
  {
    emotionTags: ['fabulous'],
    isGif: false,
    image: 'fabulous.jpeg',
    alt: 'A cat looking fabulous',
  },
  {
    emotionTags: ['fabulous'],
    isGif: false,
    image: 'fabulous2.jpeg',
    alt: 'A cat looking fabulous',
  },
  {
    emotionTags: ['fabulous'],
    isGif: false,
    image: 'fabulous3.jpeg',
    alt: 'A cat looking fabulous',
  },
  {
    emotionTags: ['fabulous'],
    isGif: true,
    image: 'fabulous.gif',
    alt: 'A cat looking fabulous',
  },
  {
    emotionTags: ['fabulous'],
    isGif: true,
    image: 'fabulous2.gif',
    alt: 'A cat looking fabulous',
  },

  {
    emotionTags: ['fabulous', 'cool'],
    isGif: false,
    image: 'cool-fabulous2.jpeg',
    alt: 'A cat looking fabulous and cool',
  },
  {
    emotionTags: ['fabulous', 'cool'],
    isGif: false,
    image: 'cool-fabulous3.jpeg',
    alt: 'A cat looking fabulous and cool',
  },
  {
    emotionTags: ['cool'],
    isGif: true,
    image: 'cool.gif',
    alt: 'A cat looking cool',
  },
  {
    emotionTags: ['cool'],
    isGif: true,
    image: 'cool2.gif',
    alt: 'A cat looking cool',
  },
  {
    emotionTags: ['cool'],
    isGif: true,
    image: 'cool3.gif',
    alt: 'A cat looking cool',
  },
  {
    emotionTags: ['cool'],
    isGif: false,
    image: 'cool.jpeg',
    alt: 'A cat looking cool',
  },
  {
    emotionTags: ['cool'],
    isGif: false,
    image: 'cool2.jpeg',
    alt: 'A cat looking cool',
  },
  {
    emotionTags: ['confused'],
    isGif: false,
    image: 'confused.jpg',
    alt: 'A cat looking confused',
  },
  {
    emotionTags: ['dominant'],
    isGif: false,
    image: 'dominant.jpeg',
    alt: 'A cat looking dominant',
  },
  {
    emotionTags: ['dominant'],
    isGif: true,
    image: 'dominant.gif',
    alt: 'A cat looking dominant',
  },
  {
    emotionTags: ['dominant', 'moody'],
    isGif: true,
    image: 'dominant2.gif',
    alt: 'A cat looking dominant',
  },
  {
    emotionTags: ['dominant'],
    isGif: false,
    image: 'dominant3.jpeg',
    alt: 'A cat looking dominant',
  },
  {
    emotionTags: ['dominant'],
    isGif: false,
    image: 'dominant2.jpeg',
    alt: 'A cat looking dominant',
  },
  {
    emotionTags: ['hungry', 'dominant'],
    isGif: false,
    image: 'hungry-dominant.jpeg',
    alt: 'A cat looking hungry and dominant',
  },
  {
    emotionTags: ['hungry'],
    isGif: false,
    image: 'hungry.jpeg',
    alt: 'A cat looking hungry',
  },
  {
    emotionTags: ['hungry'],
    isGif: false,
    image: 'hungry1.jpeg',
    alt: 'A cat looking hungry',
  },
  {
    emotionTags: ['hungry'],
    isGif: true,
    image: 'hungry.gif',
    alt: 'A cat looking hungry',
  },
  {
    emotionTags: ['hungry'],
    isGif: true,
    image: 'hungry2.gif',
    alt: 'A cat looking hungry',
  },
  {
    emotionTags: ['evil'],
    isGif: false,
    image: 'evil.jpeg',
    alt: 'A cat looking evil',
  },
  {
    emotionTags: ['evil'],
    isGif: false,
    image: 'evil2.jpeg',
    alt: 'A cat looking evil',
  },
  {
    emotionTags: ['evil'],
    isGif: false,
    image: 'evil3.jpeg',
    alt: 'A cat looking evil',
  },
  {
    emotionTags: ['evil'],
    isGif: true,
    image: 'evil.gif',
    alt: 'A cat looking evil',
  },
  {
    emotionTags: ['evil', 'happy'],
    isGif: true,
    image: 'happy-evil.gif',
    alt: 'A cat looking evil and happy',
  },
  {
    emotionTags: ['happy'],
    isGif: true,
    image: 'happy.gif',
    alt: 'A cat looking happy',
  },
  {
    emotionTags: ['happy'],
    isGif: true,
    image: 'happy2.gif',
    alt: 'A cat looking happy',
  },
  {
    emotionTags: ['happy', 'relaxed'],
    isGif: false,
    image: 'happy.jpeg',
    alt: 'A cat looking happy',
  },
  {
    emotionTags: ['lazy'],
    isGif: false,
    image: 'lazy.jpeg',
    alt: 'A cat looking lazy',
  },
  {
    emotionTags: ['lazy'],
    isGif: true,
    image: 'lazy.gif',
    alt: 'A cat looking relaxed',
  },
  {
    emotionTags: ['lazy'],
    isGif: false,
    image: 'lazy2.jpeg',
    alt: 'A cat looking lazy',
  },
  {
    emotionTags: ['lazy'],
    isGif: false,
    image: 'lazy3.jpeg',
    alt: 'A cat looking lazy',
  },
  {
    emotionTags: ['lazy', 'relaxed'],
    isGif: false,
    image: 'lazy4.jpeg',
    alt: 'A cat looking lazy',
  },
  {
    emotionTags: ['lazy', 'relaxed'],
    isGif: false,
    image: 'lazy5.jpeg',
    alt: 'A cat looking lazy and relaxed',
  },
  {
    emotionTags: ['lazy', 'relaxed'],
    isGif: false,
    image: 'lazy6.jpeg',
    alt: 'A cat looking lazy and relaxed',
  },
  {
    emotionTags: ['lazy', 'relaxed'],
    isGif: true,
    image: 'lazy-relaxed.gif',
    alt: 'A cat looking lazy and relaxed',
  },
  {
    emotionTags: ['lazy', 'relaxed'],
    isGif: true,
    image: 'lazy-relaxed2.gif',
    alt: 'A cat looking lazy and relaxed',
  },
  {
    emotionTags: ['relaxed'],
    isGif: true,
    image: 'relaxed2.gif',
    alt: 'A cat looking relaxed',
  },
  {
    emotionTags: ['relaxed'],
    isGif: true,
    image: 'relaxed3.gif',
    alt: 'A cat looking relaxed',
  },
  {
    emotionTags: ['scared'],
    isGif: false,
    image: 'nervous.jpeg',
    alt: 'A cat looking nervous',
  },
  {
    emotionTags: ['scared'],
    isGif: true,
    image: 'scared.gif',
    alt: 'A cat looking nervous',
  },
  {
    emotionTags: ['scared', 'confused'],
    isGif: true,
    image: 'scared-confused.gif',
    alt: 'A cat looking nervous',
  },

  {
    emotionTags: ['confused'],
    isGif: true,
    image: 'confused2.gif',
    alt: 'A cat looking confused',
  },
  {
    emotionTags: ['confused', 'scared'],
    isGif: true,
    image: 'confused3.gif',
    alt: 'A cat looking confused',
  },
  {
    emotionTags: ['confused'],
    isGif: true,
    image: 'confused4.gif',
    alt: 'A cat looking confused',
  },
  {
    emotionTags: ['confused'],
    isGif: true,
    image: 'confused5.gif',
    alt: 'A cat looking confused',
  },
  {
    emotionTags: ['confused'],
    isGif: true,
    image: 'confused6.gif',
    alt: 'A cat looking confused',
  },
  {
    emotionTags: ['confused'],
    isGif: false,
    image: 'confused5.jpg',
    alt: 'A cat looking confused',
  },

  {
    emotionTags: ['scared', 'sad'],
    isGif: true,
    image: 'scared2.gif',
    alt: 'A cat looking nervous',
  },
  {
    emotionTags: ['sad'],
    isGif: true,
    image: 'sad2.gif',
    alt: 'A cat looking nervous',
  },
  {
    emotionTags: ['sad'],
    isGif: false,
    image: 'sad.jpeg',
    alt: 'A cat looking sad',
  },
  {
    emotionTags: ['sad'],
    isGif: false,
    image: 'sad2.jpeg',
    alt: 'A cat looking sad',
  },
  {
    emotionTags: ['sad'],
    isGif: true,
    image: 'sad.gif',
    alt: 'A cat looking sad',
  },
  {
    emotionTags: ['sad'],
    isGif: false,
    image: 'sad3.jpeg',
    alt: 'A cat looking sad',
  },
];
